-- MySQL Script generated by MySQL Workbench
-- Wed May 28 11:14:30 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id INT` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id INT`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`publicacoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`publicacoes` (
  `id` INT NOT NULL,
  `nome_prato` VARCHAR(255) NOT NULL,
  `pratoscol` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(255) NOT NULL,
  `local` VARCHAR(255) NOT NULL,
  `cidade_estado` VARCHAR(45) NOT NULL,
  `publicacoescol` VARCHAR(45) NOT NULL,
  `usuarios_id INT` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_publicacoes_usuarios1_idx` (`usuarios_id INT` ASC) VISIBLE,
  CONSTRAINT `fk_publicacoes_usuarios1`
    FOREIGN KEY (`usuarios_id INT`)
    REFERENCES `mydb`.`usuarios` (`id INT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id` INT NOT NULL,
  `comentarios` VARCHAR(255) NOT NULL,
  `data` DATETIME NOT NULL,
  `foto_perfil` VARCHAR(255) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `data_comentario` DATETIME NOT NULL,
  `comentarioscol` VARCHAR(45) NOT NULL,
  `comentarios_id` INT NOT NULL,
  `usuarios_id INT` INT NOT NULL,
  `publicacoes_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comentarios_usuarios_idx` (`usuarios_id INT` ASC) VISIBLE,
  INDEX `fk_comentarios_publicacoes1_idx` (`publicacoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuarios`
    FOREIGN KEY (`usuarios_id INT`)
    REFERENCES `mydb`.`usuarios` (`id INT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comentarios_publicacoes1`
    FOREIGN KEY (`publicacoes_id`)
    REFERENCES `mydb`.`publicacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reacoes_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reacoes_usuario` (
  `reacoes ENUM` INT NOT NULL,
  `usuarios_id INT` INT NOT NULL,
  `publicacoes_id` INT NOT NULL,
  INDEX `fk_reacoes_usuario_usuarios1_idx` (`usuarios_id INT` ASC) VISIBLE,
  INDEX `fk_reacoes_usuario_publicacoes1_idx` (`publicacoes_id` ASC) VISIBLE,
  CONSTRAINT `fk_reacoes_usuario_usuarios1`
    FOREIGN KEY (`usuarios_id INT`)
    REFERENCES `mydb`.`usuarios` (`id INT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reacoes_usuario_publicacoes1`
    FOREIGN KEY (`publicacoes_id`)
    REFERENCES `mydb`.`publicacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
